window.SB_TRIP = Object.freeze({
  start: "2026-10-01",
  wedding: "2026-10-10",
  end: "2026-10-18",
  contacts: [{"name": "Gina", "phone": "+17209886100"}, {"name": "Mike", "phone": "+17205822348"}, {"name": "Anna", "phone": "+13037094748"}, {"name": "Megan", "phone": "+13036817763"}, {"name": "Katie", "phone": "+17204026311"}, {"name": "Brendon", "phone": "+17209269641"}, {"name": "Cindy", "phone": "+13035185791"}, {"name": "Sierra", "phone": "+17208296759"}, {"name": "Sera", "phone": "+17204403433"}, {"name": "Alex", "phone": "+13033302268"}, {"name": "Colleen", "phone": "+17038485194"}],
  stays: {
    verona: {address:"Via del Minatore, 5, 37122 Verona VR, Italy", listing:"https://www.airbnb.com/rooms/33595017", name:"Raggio di Luna Apartment", area:"Verona", page:"verona.html", timing:"Check-in after 12:00 PM on Oct 1 • Checkout by 11:00 AM on Oct 4", timingStatus:"Confirmed booking"},
    parma: {address:"Borgo Montassù, 3, Parma, Emilia-Romagna, Italy", listing:"https://www.airbnb.com/rooms/1684795982326693057", name:"Casa Nadia / 150 MQ Apartment + Depandance", area:"Parma", page:"parma.html", timing:"Check-in after 3:00 PM on Oct 4 • Checkout by 10:00 AM on Oct 7", timingStatus:"Confirmed booking"},
    ispraGuest: {address:"Via Valcanale 297, 21027 Ispra VA, Italy", listing:"https://www.airbnb.com/rooms/51341531", name:"Guest / friends villa", area:"Ispra / Lake Maggiore", page:"ispra.html", timing:"Check-in after 3:00 PM on Oct 7 • Checkout by 10:00 AM on Oct 11", timingStatus:"Confirmed booking"},
    ispraWedding: {address:"Via Valcanale 504, 21027 Ispra VA, Italy", listing:"https://www.emmavillas.com/en/lombardy/villa-eden-8", name:"Villa Eden 8", area:"Ispra / Lake Maggiore", page:"ispra.html", timing:"Check-in 4:00 PM on Oct 7 • Check-out 10:00 AM on Oct 11", timingStatus:"Confirmed booking"},
    gemmas: {address:"Via Milite Ignoto 18, 21027 Ispra VA, Italy", listing:"https://www.airbnb.com/rooms/870230713012084522", name:"Gemma’s Nest", area:"Ispra", page:"ispra.html", timing:"Check-in 3:00 PM on Oct 10 • Checkout 10:00 AM on Oct 11", timingStatus:"Current booking details"},
    santa: {address:"Via Partigiani D'Italia, 25, 16038 Santa Margherita Ligure, Liguria, Italy", listing:"https://vrbo.onelink.me/ItNz/9pc2qq6n", name:"Painted Blue by PortofinoVip", area:"Santa Margherita Ligure", page:"santa-margherita.html", timing:"Check-in after 3:00 PM on Oct 11 • Checkout around 10:00 AM on Oct 14", timingStatus:"Current booking plan"},
    beaulieu: {address:"13 Boulevard Eugène Gauthier, Les Constellations – Bloc C, 06310 Beaulieu-sur-Mer, France", listing:"https://vrbo.onelink.me/ItNz/cnrblsn1", name:"Mila — Penthouse for 2", area:"Beaulieu-sur-Mer", page:"nice.html", timing:"Host handoff after our 3:26 PM arrival on Oct 14 • Planned departure around 9:00 AM on Oct 18", timingStatus:"Arrival plan — confirm host handoff"}
  },
  days: {
    "2026-10-01": {pack:["Passport + wallet","Phone + charger/power bank","Comfortable travel shoes","Light layer","Daily meds"], city:"Verona", stayKey:"verona", idea:"Arrive + meet Verona slowly", ideaDetail:"Taxi straight to the apartment, easy historic-center walk, Il Vicoletto if we want dinner out.", ideaLink:"verona.html#things-to-do", transport:"Arrive in Verona", transportDetail:"VRN 12:45 PM • direct taxi is the low-hassle default", transportLink:"transportation.html#oct-01"},
    "2026-10-02": {pack:["Comfortable walking shoes","Light layer / packable rain shell","Small day bag","Show ticket","Sunglasses"], city:"Verona", stayKey:"verona", idea:"Arena + sunset + big night", ideaDetail:"Arena before 3 PM closure • Bugiardo aperitivo • Castel San Pietro sunset • Notre Dame 9 PM.", ideaLink:"verona.html#events", transport:"Next travel: Parma", transportDetail:"Oct 4 • flexible train after checkout", transportLink:"transportation.html#oct-04"},
    "2026-10-03": {pack:["Comfortable walking shoes","Light layer","Small day bag","Smart-casual dinner layer"], city:"Verona", stayKey:"verona", idea:"History + best food day", ideaDetail:"10:30 English history walk • Gironda lunch • optional Lamberti • Al Pompiere dinner.", ideaLink:"verona.html#our-plan", transport:"Next travel: Parma", transportDetail:"Tomorrow • checkout by 11 AM", transportLink:"transportation.html#oct-04"},
    "2026-10-04": {pack:["Train tickets","Light layer","Water + snacks","Easy-to-carry day bag"], city:"Travel → Parma", stayKey:"parma", idea:"Check in + free Farnese if energy allows", ideaDetail:"First-Sunday Pilotta/Teatro Farnese is the best arrival-day opportunity; otherwise just settle in.", ideaLink:"parma.html#events", transport:"Verona → Parma", transportDetail:"Checkout by 11 AM • flexible train for ~3 PM check-in", transportLink:"transportation.html#oct-04"},
    "2026-10-05": {pack:["Comfortable walking shoes","Light layer","Small day bag","Dinner reservation"], city:"Parma", stayKey:"parma", idea:"Duomo + Verdi + Cocchi", ideaDetail:"Cathedral/Baptistery • 11 AM free Verdi talk • optional fair • Cocchi dinner.", ideaLink:"parma.html#our-plan", transport:"Next travel: Ispra", transportDetail:"Oct 7 • IC 580 + MXP rental pickup", transportLink:"transportation.html#oct-07"},
    "2026-10-06": {pack:["Comfortable walking shoes","Light layer","Small day bag","Event ticket","Pack travel essentials tonight"], city:"Parma", stayKey:"parma", idea:"Pepèn + Maria Luigia + Regio", ideaDetail:"Da Pepèn • Museo Glauco Lombardi • Enoteca Fontana • Regio in Tour 8:30 PM.", ideaLink:"parma.html#events", transport:"Tomorrow: Ispra", transportDetail:"IC 580 • Parma 10:39 AM → Milan 12:15 PM", transportLink:"transportation.html#oct-07"},
    "2026-10-07": {pack:["Passport + tickets","Driver license + IDP","Rental voucher","Phone charger/power bank","Light layer"], city:"Travel → Ispra", stayKey:"ispraWedding", idea:"Villa arrival + supply run", ideaDetail:"Pick up the booked rental at MXP, settle in, then use a car for groceries if needed.", ideaLink:"ispra.html#transport", transport:"Parma → Milan → MXP → Ispra", transportDetail:"IC 580 10:39 → 12:15 • rental pickup 3:00 PM", transportLink:"transportation.html#oct-07"},
    "2026-10-08": {pack:["Comfortable shoes","Light layer / rain shell","Sunglasses","Small lake-day bag"], city:"Ispra / Lake Maggiore", stayKey:"ispraWedding", idea:"Santa Caterina del Sasso", ideaDetail:"Closest high-value excursion; drive there, use the lift if desired, and keep the rest of the day flexible.", ideaLink:"ispra.html#things-to-do", transport:"Local driving day", transportDetail:"Rental cars are the default • Stresa only if autumn island boats are confirmed", transportLink:"ispra.html#transport"},
    "2026-10-09": {pack:["Wedding prep bag","Comfortable shoes","Light layer","Anything needed for ceremony setup"], city:"Ispra", stayKey:"ispraWedding", idea:"Wedding-eve buffer", ideaDetail:"Ispra waterfront/Fornaci • optional Angera only if prep is under control • supplies/laundry.", ideaLink:"ispra.html#our-plan", transport:"Next travel: Santa Margherita", transportDetail:"Oct 11 • return car(s) + IC 665", transportLink:"transportation.html#oct-11"},
    "2026-10-10": {pack:["Wedding attire","Rings","Vows / ceremony notes","Touch-up kit","Comfortable backup shoes","Phone charger"], city:"Wedding Day 💍", stayKey:"gemmas", idea:"Get married", ideaDetail:"Marta’s plan: getting ready 3–4 PM → ceremony 4–4:30 PM → couple/group photos 4:30–6 PM → aperitivo + first dance 6–7 PM. Colleen: officiant. Alex: best man and rings. Sierra: music. Anna: meet Marta. Cindy: champagne. Megan: restaurant departure. Dinner confirmed at Ristorante dei Limoni around 8 PM for 11 people.", ideaLink:"wedding.html", transport:"Tomorrow: Ligurian coast", transportDetail:"Return rental(s) → Milan → IC 665", transportLink:"transportation.html#oct-11"},
    "2026-10-11": {pack:["Train tickets","Rental return documents","Phone charger/power bank","Light layer","Water + snacks"], city:"Travel → Santa Margherita", stayKey:"santa", idea:"Arrive + exhale", ideaDetail:"Check in after 3, waterfront walk, aperitivo and a romantic Santa dinner.", ideaLink:"santa-margherita.html#overview", transport:"Ispra → MXP → Milan → Santa", transportDetail:"IC 665 • Milan 12:10 PM → Santa 2:16 PM", transportLink:"transportation.html#oct-11"},
    "2026-10-12": {pack:["Comfortable walking shoes","Light layer / rain shell","Sunglasses","Small day bag"], city:"Santa Margherita Ligure", stayKey:"santa", idea:"Portofino toward sunset", ideaDetail:"Slow Santa morning • ferry out if operating • Castello Brown OR lighthouse • bus 782 back.", ideaLink:"santa-margherita.html#daytrips", transport:"Portofino local plan", transportDetail:"Ferry preferred out • bus 782 is the dependable evening fallback", transportLink:"transportation.html#local-riviera"},
    "2026-10-13": {pack:["Comfortable walking shoes","Light layer","Small day bag","Laundry items"], city:"Santa Margherita Ligure", stayKey:"santa", idea:"Camogli golden hour", ideaDetail:"Slow morning/laundry • direct train to Camogli • sunset • final Italian honeymoon dinner.", ideaLink:"santa-margherita.html#daytrips", transport:"Next travel: France", transportDetail:"Tomorrow • first booked train 10:14 AM", transportLink:"transportation.html#oct-14"},
    "2026-10-14": {pack:["Train tickets","Passport","Phone charger/power bank","Light layer","Water + snacks"], city:"Travel → Beaulieu-sur-Mer", stayKey:"beaulieu", idea:"Arrive + Beaulieu sunset", ideaDetail:"Arrive 3:26 PM, meet host, then keep the first French evening local.", ideaLink:"nice.html#beaulieu", transport:"Santa → Beaulieu", transportDetail:"10:14 → 11:02 • 11:35 → 2:12 • 2:40 → 3:26", transportLink:"transportation.html#oct-14"},
    "2026-10-15": {pack:["Grippy walking shoes","Light layer / rain shell","Sunglasses","Small day bag","Water"], city:"Èze / Beaulieu", stayKey:"beaulieu", idea:"Èze by bus, not by hike", ideaDetail:"Bus 83 from Baie des Fourmis • medieval village • Exotic Garden • easy bus return.", ideaLink:"nice.html#eze", transport:"Èze day", transportDetail:"Verify line 83 the night before; avoid the Nietzsche Path unless we actively want a climb", transportLink:"transportation.html#local-riviera"},
    "2026-10-16": {pack:["Comfortable walking shoes","Light outer layer","Small day bag","Water"], city:"Beaulieu / Cap-Ferrat", stayKey:"beaulieu", idea:"Kérylos + Ephrussi", ideaDetail:"Villa Kérylos • Maurice Rouvier coastal walk • Villa Ephrussi • bus back if tired.", ideaLink:"nice.html#beaulieu", transport:"Local day", transportDetail:"Walk most of it • bus 15 is the easy return option", transportLink:"transportation.html#local-riviera"},
    "2026-10-17": {pack:["Comfortable walking shoes","Light layer","Sunglasses","Small day bag","Nicer evening layer"], city:"Nice", stayKey:"beaulieu", idea:"Old Nice + dance finale", ideaDetail:"Vieux Nice • socca • Castle Hill • Promenade • ballet or CaraïbAzur at night.", ideaLink:"nice.html#nice-day", transport:"Beaulieu ↔ Nice", transportDetail:"Use TER for the city day; return to quiet Beaulieu afterward", transportLink:"transportation.html#local-riviera"},
    "2026-10-18": {pack:["Passport","Phone + charger","Travel documents","Light layer","Anything needed for the flight"], city:"Fly home ✈️", stayKey:"beaulieu", idea:"Make the airport boring", ideaDetail:"Checkout around 9 AM; arrange a taxi/VTC in advance; TER + free airport tram is backup.", ideaLink:"transportation.html#oct-18", transport:"Beaulieu → NCE Terminal 2", transportDetail:"Plan: arrange a car around 9 AM • flight 12:35 PM", transportLink:"transportation.html#oct-18"}
  },
  travelDays: [
    {date:"Oct 1", status:"Booked flight", title:"VRN airport → Verona", detail:"Arrive 12:45 PM. Direct taxi to the apartment is the lowest-hassle default for the four-person arrival group.", link:"transportation.html#oct-01"},
    {date:"Oct 4", status:"Flexible", title:"Verona → Parma", detail:"Checkout by 11:00 AM; choose a comfortable train that lands near the 3:00 PM check-in window.", link:"transportation.html#oct-04"},
    {date:"Oct 7", status:"Booked core legs", title:"Parma → Milan → MXP → Ispra", detail:"IC 580: 10:39 AM → 12:15 PM. Booked Hertz rental pickup at MXP Terminal 1 at 3:00 PM.", link:"transportation.html#oct-07"},
    {date:"Oct 11", status:"Booked train", title:"Ispra → MXP → Milan → Santa Margherita", detail:"Return rental car(s) with buffer, then IC 665: Milano Centrale 12:10 PM → Santa Margherita 2:16 PM.", link:"transportation.html#oct-11"},
    {date:"Oct 14", status:"All booked", title:"Santa Margherita → Beaulieu-sur-Mer", detail:"10:14 → 11:02 Genova Brignole; 11:35 → 2:12 Ventimiglia; 2:40 → 3:26 Beaulieu.", link:"transportation.html#oct-14"},
    {date:"Oct 18", status:"Booked flight", title:"Beaulieu → Nice Airport", detail:"Checkout around 9:00 AM. Arrange a taxi/VTC in advance; TER to Nice Saint-Augustin + free airport tram is backup.", link:"transportation.html#oct-18"}
  ]
});


